### ISSUE TITLE
相似搜索爱好者， 请多多指教

### ISSUE THREAD

**Issue by ChunelFeng** [leovan/leovan.me#2]
大佬您好，在网上搜索资料的时候，看到了您的成果，非常赞。我们现在正在做一款相似搜索引擎，希望能得到您的指教。源码和我们的联系方式：https://github.com/ChunelFeng/caiss （无法在您的博客找到您的微信等联系方式，希望能联系上您）

**Comment by leovan** [comment]
很庆幸博客能对您有些帮助，最近邻搜索在工业界确实很多应用场景，我个人也只是浮于上层的应用，更谈不上指教了。看到了您的 repo，很棒的工作，也很高兴有机会能够交流，个人比较喜欢邮件交流，me # leovan.me，欢迎随时沟通，回复有时会慢些，见谅。
