### ISSUE TITLE
pseudocode无法渲染

### ISSUE THREAD

**Issue by sherlcok314159** [leovan/leovan.me#23]
看了您的博客中伪代码的渲染，真是很好看，同是Hugo，于是我复刻了您的一切操作，比如footer，mathjax，jQuery，shortcode等，然而还是不能work，请问您对Hugo本身不能渲染$1$这种是如何处理的呢？

或者是查看[pseudocode.js](https://github.com/SaswatPadhi/pseudocode.js)官网，能详细说下当时您配置与官网步骤不同的地方吗

感激不尽~

**Comment by leovan** [comment]
目前网站中的一些配置比较多，如果你完全 clone 了代码，跑起来应该是没问题了，但把一些配置或 shortcode 放到你自己的网站中，可能得慢慢调试看看了。

关于 Hugo 中使用 Mathjax，采用的方式是 Markdown 中使用 ` 号把 Mathjax 代码包裹起来，[math-code.js](https://github.com/leovan/leovan.me/blob/main/static/js/math-code.js) 负责把它还原并用 Mathjax 渲染。在 pseudocode.js 中的数学表达式不用 ` 号，正常写就行。

pseudocode.js 没有做额外的配置，参考官网即可，可能需要注意的是要在 pseudocode.js 之前引入 mathjax 的 JS 代码并初始化 Mathjax。

如上，是可能存在的问题，希望可以帮到你。
