### ISSUE TITLE
关于静态网站

### ISSUE THREAD

**Issue by invisiblecloak-slw** [leovan/leovan.me#3]
您好！在搜索LLE的过程中浏览到您的博客，被深深吸引。于是来到您的Github主页上看是否有博客的模版。请问怎样才能做到您博客这样精美的程度呢，大佬是否可以提供一下模版？不过“似我者生，类我者死”。倘若能够在您这学到一点关于搭建博客的知识，也倍感幸运，谢谢您啦！

**Comment by leovan** [comment]
您好，很高兴自己的网站能够对您有些许帮助。这个 repo 包含了构建个人网站的所有代码。主要是利用 R 的 blogdown 扩展包（https://bookdown.org/yihui/blogdown/）构建，如果您对 R 不熟悉，其实这个扩展包是对 hugo （https://gohugo.io/）的一个上层封装。主题是修改自 https://github.com/yihui/hugo-ivy，修改部分可以参见 repo 中的 css 和 javascript 代码。blogdown 和 hugo 的使用方式在相应的官网都有教程。

**Comment by invisiblecloak-slw** [comment]
感谢!
