### ISSUE TITLE
博客好赞，希望能认识一下

### ISSUE THREAD

**Issue by CharlesLiuyx** [leovan/leovan.me#34]
Leo 你好，我是刘遥行，看到博客，非常喜欢这个风格，希望能加个微信交个朋友~ （微信号：uranus_lyx）

现在在创业做无代码工具，https://dora.run，最近刚刚拿到了 Product Hunt [双榜第一](https://www.producthunt.com/posts/dora-ai-alpha)。天使轮高瓴和奇绩创坛的千万级融资。

前幕布产品负责人，幕布被字节跳动收购后，在字节跳动待了 2 年多。然后创业。

**Comment by leovan** [comment]
谢谢，很高兴认识
