### ISSUE TITLE
关于mrpt方法中投票内容的咨询

### ISSUE THREAD

**Issue by ChunelFeng** [leovan/leovan.me#4]
https://github.com/vioshyvo/mrpt  大佬，看到您在ann方面很有造诣。
想咨询一下，如何理解mrpt算法中，在查询过程中的投票（vote）机制。
论文和代码都没读明白，只了解到vote_threshold值越大，查询越快，但结果越不准确。

**Comment by leovan** [comment]
很抱歉这个问题帮不上你，对于 ANN 我大部分停留在应用层面，很多算法细节都不甚了解。

**Comment by ChunelFeng** [comment]
thx all the same
