### ISSUE TITLE
您好，请问主页上“手中有佛，心中有刀”上面的logo应该怎么修改替换？

### ISSUE THREAD

**Issue by auravan** [leovan/leovan.me#44]
前辈您好，很喜欢您做的主页。我在fork之后自己修改碰到了一些问题，我找到了所有相关的icon用我自己的内容进行了替换，但是这个主页上的logo就是不改变，请问这个应该怎么修改。（原谅我糟糕的go和html语言技能）
![image](https://github.com/user-attachments/assets/c9542d2c-21f0-4801-9f6d-6cbb62a57b8d)

另外想请教您如果fork了之后，按照license开源之后我在应该主页哪里提及您比较好，谢谢。

**Comment by auravan** [comment]
您好，我成功了。我用codiem(一个copilot的替代品)告诉我项目结构，我在"leovan.me-main\layouts\partials\header_logo.html"这个页面进行修改，成功了。但是不知道为什么原来这里没有任何代码依然可以显示logo。如果您愿意可以看一下，不知道算不算bug，还算蛮有意思。
![image](https://github.com/user-attachments/assets/8c8b824d-e975-4e72-9e4b-76c835006b31)

**Comment by leovan** [comment]
网站做了明亮和暗黑的适配，涉及到的 Logo 的图像都在这个目录：

<img width="324" alt="image" src="https://github.com/user-attachments/assets/0e284865-18d7-45d9-bd5d-0ac8b8f36ceb">

很多 JS 脚本用应该也有用到，你可能得在整个工程中做一下搜索了，很多细节我也记不太清楚了。
