### ISSUE TITLE
关于hugo-ivy模版首页的文章链接显示问题

### ISSUE THREAD

**Issue by invisiblecloak-slw** [leovan/leovan.me#5]
您好！Hugo-ivy模版有这样一段话：

All pages not under the root directory of the website are listed below. You can also visit the list page of a single section, e.g., [posts](/post/), or [notes](/note/).

请问应该怎样操作，使得首页不显示博文链接，而是放到导航栏中的 /分类 或 /标签 中来查阅呢？

感谢！

**Comment by leovan** [comment]
首页也是 list 页面，你可以修改 `layouts/_default/list.html` 修改所有 list 页面渲染方式。如果需要对首页做特殊操作，可以使用 `{{ if .IsHome }}` 方式判断。

**Comment by invisiblecloak-slw** [comment]
谢谢您帮助，祝好～！
