### ISSUE TITLE
关于<pseudocode>

### ISSUE THREAD

**Issue by tcxia** [leovan/leovan.me#6]
大神，想问一下如何配置markdown来支持pseudocode，我一般使用atom写md，能透露你使用的编辑器吗？

**Comment by leovan** [comment]
pseudocode 代码块的预览是利用了 Hugo 中的 shortcode 实现的，没法在 markdown 中原生的支持。我是用 RStudio 或 VS Code 来写，利用 Hugo 可以实时预览的（RStuido 这部分已经可以自动实现，源代码发生变化保存后，Hugo 自动更新预览）。如果想在一些其他所见即所得编辑器（例如：Typora）中预览，估计得配合 CSS 和 JS 做一些工具修改了。

**Comment by tcxia** [comment]
了解，感谢感谢

发自我的iPhone
