### ISSUE TITLE
请问能使用您的网站模板吗？

### ISSUE THREAD

**Issue by TianjieZhang1993** [leovan/leovan.me#7]
如果可以的话，怎么使用呢？直接复制好像没法用github的pages功能

**Comment by leovan** [comment]
可以，完全没问题，我也是从 https://github.com/yihui/hugo-ivy 模板慢慢一点点修改的，我没有用 github 的 pages 部署网站，用的是 cloudflare 的 pages，github 的按照说明添加一些配置应该就能用吧，不过应该得再配置一些自动化采用用 hugo 把网站编译好。

**Comment by xiongus** [comment]
已在使用，感谢开源提供。
